def send_startup_message(ch):
    ch.send("CLEARSCREEN")
    ch.send("INFO Starting...")
    ch.send("WARNING \n   _______  ____  ______")
    ch.send("WARNING   / __/ _ \\/ __ \\/_  __/")
    ch.send("WARNING  _\\ \\/ ___/ /_/ / / /")
    ch.send("WARNING /___/_/   \\____/ /_/")  
    ch.send("WARNING SOFTWARE PLATFORM for")
    ch.send("WARNING ONBOARD TELEMETRY")
    ch.send("INFO \nDesigned for the:")
    ch.send("WARNING \n⣏⡉ ⡎⢱ ⡇⢸ ⡇ ⡷⣸ ⡎⢱ ⢇⡸")
    ch.send("WARNING ⠧⠤ ⠣⠪ ⠣⠜ ⠇ ⠇⠹ ⠣⠜ ⠇⠸")
    ch.send("WARNING SOFTWARE STACK\n\n")